### USER
GET http://localhost:3000/api/v1/contacts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im9udXJoYW5AdGVzdC5jb20iLCJpYXQiOjE2NDgwNDc0NzN9.UVFGOpPXQD_l23qeT7Moxcy6gBGJGjCKXDGOUWT8aQg

###
GET http://localhost:3000/api/v1/contacts/search/1/work jane
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im9udXJoYW5AdGVzdC5jb20iLCJpYXQiOjE2NDgwNDc0NzN9.UVFGOpPXQD_l23qeT7Moxcy6gBGJGjCKXDGOUWT8aQg

###
GET http://localhost:3000/api/v1/contactsByUserId/1


###
GET http://localhost:3000/api/v1/contact/1


###
DELETE http://localhost:3000/api/v1/contact/1


###
PUT http://localhost:3000/api/v1/contact
Content-Type: application/json

{
    "id": "5",
    "userId": "7",
    "phoneNumbers": [
        { "type": "Cell", "number": 2223334444 },
        { "type": "Work", "number": 3334445555 }
    ]
}


###
POST http://localhost:3000/api/v1/contact
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im9udXJoYW5AdGVzdC5jb20iLCJpYXQiOjE2NDgwNDc0NzN9.UVFGOpPXQD_l23qeT7Moxcy6gBGJGjCKXDGOUWT8aQg

{
    "userId": 1,
    "firstName": "Jane",
    "lastName": "Doe",
    "company": "mobilist",
    "phoneNumbers": [
        { "type": "Cell", "number": 2223334444 },
        { "type": "Work", "number": 3334445555 }
    ]
}
